server {
    listen 80;

    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location /health {
        access_log off;
        default_type text/plain;
        return 200 'healthy\n';
    }

    #
    # AUTH SERVICE
    #
    location /user/login {
        proxy_pass http://goblin-security:8089/user/login;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /user/register {
        proxy_pass http://goblin-security:8089/user/register;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    #
    # LEDGER SERVICE
    #
    location /user/profile {
        proxy_pass http://goblin-ledger:8088/user/profile;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /user/contacts {
        proxy_pass http://goblin-ledger:8088/user/contacts;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    #
    # LIVEKIT SERVICE
    #

#     location /rooms {
#         proxy_pass http://livekit-server:7880;
#         proxy_set_header Host $host;
#         proxy_set_header X-Real-IP $remote_addr;
#     }
#
#     location /rooms/token {
#         proxy_pass http://livekit-server:7880;
#         proxy_set_header Host $host;
#         proxy_set_header X-Real-IP $remote_addr;
#     }

    #
    # FRONTEND SPA
    #
    location / {
        try_files $uri /index.html;
    }
}