# postgres-deployment.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goblinledger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goblinledger
  template:
    metadata:
      labels:
        app: goblinledger
    spec:
      containers:
        - name: postgres
          image: postgres:16
          env:
            - name: POSTGRES_USER
              value: "admin"
            - name: POSTGRES_PASSWORD
              value: "penguin"
            - name: POSTGRES_DB
              value: "GoblinTime"
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: goblinledger
spec:
  selector:
    app: goblinledger
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
