apiVersion: v1
kind: Secret
metadata:
  name: goblin-secrets
type: Opaque
data:
  # "host=GoblinLedger user=admin password=penguin dbname=GoblinTime port=5432 sslmode=disable" base64 encoded:
  database-url: aG9zdD1Hb2JsaW5MZWRnZXIgdXNlcj1hZG1pbiBwYXNzd29yZD1wZW5ndWluIGRibmFtZT1Hb2JsaW5UaW1lIHBvcnQ9NTQzMiBzc2xtb2RlPWRpc2FibGU=

  # "goblin" base64 encoded:
  jwt-secret: Z29ibGlu