apiVersion: v1
kind: Secret
metadata:
  name: goblin-secrets
type: Opaque
data:
  # "user=admin password=penguin" base64 encoded:
  db-credentials: dXNlcj1hZG1pbiBwYXNzd29yZD1wZW5ndWlu

  # "goblin" base64 encoded:
  JWT_SECRET: Z29ibGlu