apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice-deployment
  labels:
    app: userservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: userservice
  template:
    metadata:
      labels:
        app: userservice
    spec:
      containers:
        - name: ledger-manager
          image: xpenguingodx/userservice:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8088
          env:
            # Combines the ConfigMap string and the Secret string into the exact format GORM expects!
            - name: DB_URL
              value: "$(DB_CONFIG) $(DB_CREDS)"

            # Pulls the public host and database settings
            - name: DB_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: goblin-config
                  key: db-config-string

            # Pulls the sensitive username and password credentials
            - name: DB_CREDS
              valueFrom:
                secretKeyRef:
                  name: goblin-secrets
                  key: db-credentials